### ISSUE TITLE
Extra closing </strong>

### ISSUE THREAD

**Issue by jeremypaavola** [senff/Zendesk-Check-Open-Tickets#2]
Hi there - 

I was making some personal changes to your (great) script and noticed an extra closing`</strong>` element as noted below (the final `</strong>` at the end of the line.:

https://github.com/senff/Zendesk-Check-Open-Tickets/blob/b9b99fe9d58b76e2c8020e3a5910624d755db988/zendesk-check-open-tickets.user.js#L43

Not sure if it's intentional, but I couldn't find a corresponding open `<strong>` element so wanted to note.

**Comment by senff** [comment]
Indeed, leftover from old code! Fixed now, thanks! :)
